PKG_NAME={{ pkg.name }}
PKG_URL={{ pkg.url }}
PKG_VERSION={{ pkg.hash }}
PKG_LICENSE={{ pkg.pkg_license }}

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -f $(PKG_BUILDDIR)/$(PKG_NAME).mk -C $(PKG_BUILDDIR)
