include ../Makefile.tests_common

# dependencies
{% if test.modules|length > 0 %}

# required modules
{% for module in test.modules %}
USEMODULE += {{ module }}
{% endfor %}
{% endif %}
{% if test.features|length > 0 %}

# required features
{% for feature in test.features %}
FEATURES_REQUIRED += {{ feature }}
{% endfor %}
{% endif %}
{% if test.packages|length > 0 %}

# required packages
{% for package in test.packages %}
USE_PKG += {{ package }}
{% endfor %}
{% endif %}

include $(RIOTBASE)/Makefile.include
