# name of the application
APPLICATION = {{ context.example.name }}

# If no BOARD is found in the environment, use this default:
BOARD ?= {{ context.example.board }}

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..
{% if context.example.modules|length > 0 %}

# required modules
{% for module in context.example.modules %}
USEMODULE += {{ module }}
{% endfor %}
{% endif %}
{% if context.example.features|length > 0 %}

# required features
{% for feature in context.example.features %}
FEATURES_REQUIRED += {{ feature }}
{% endfor %}
{% endif %}
{% if context.example.packages|length > 0 %}

# required packages
{% for package in context.example.packages %}
USE_PKG += {{ package }}
{% endfor %}
{% endif %}

# Comment this out to disable code in RIOT that does safety checking
# which is not needed in a production environment but helps in the
# development process:
DEVELHELP ?= 1

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
