name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '30 7 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox wheel
    - name: Test with tox
      run: tox -e tests
    - name: Test cli
      if: matrix.os != 'windows-latest'
      run: tox -e cli
    - name: Check style
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: tox -e check
    - name: Upload coverage to Codecov
      if: ${{ (matrix.python-version == 3.9) && (matrix.os == 'ubuntu-latest') }}
      run: bash <(curl -s https://codecov.io/bash)
    - name: Build a package tarball
      if: matrix.python-version == 3.9 && matrix.os == 'ubuntu-latest'
      run: python setup.py sdist bdist_wheel
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: >-
        matrix.python-version == 3.9 &&
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push' &&
        startsWith(github.event.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
