name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '30 7 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      env:
        TOXENV: py$(echo ${{ matrix.python-version }} | tr -d .)-tests
      run: tox
    - name: Test cli
      env:
        TOXENV: py$(echo ${{ matrix.python-version }} | tr -d .)-cli
      run: tox
    - name: Check style
      env:
        TOXENV: py$(echo ${{ matrix.python-version }} | tr -d .)-check
      run: tox
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./.coverage
        name: ${{ matrix.os }} Python ${{ matrix.python-version }}
        fail_ci_if_error: true
